'use strict';
// Disposable PostgreSQL only. Never import index.js, log into Discord or send live DRIP calls.
const {Pool}=require('pg');const crypto=require('node:crypto');
const {assert,harness,errorCode,IDS,Collection,fakeDiscord,extractDripCurrencyAmountFromPayload}=require('./madlibTestUtils');
const core=require('../modules/madlibCore');const {MadlibStore}=require('../modules/madlibStore');
const {MadlibEconomy}=require('../modules/madlibEconomy');const {MadlibPublishing,marker}=require('../modules/madlibPublishing');
const templates=require('../modules/madlibTemplates');const run=harness('postgres'),cfg=core.config({});
const settings={drip_realm_id:'test-realm',currency_id:'test-charm',drip_api_key:'FAKE_TEST_ONLY'};
const url=process.env.MADLIB_TEST_DATABASE_URL;
if(!url){console.log('SKIP postgres: MADLIB_TEST_DATABASE_URL is unset; database tests were not executed.');process.exit(process.env.CI?1:0);}
const parsed=new URL(url);
assert.equal(process.env.MADLIB_TEST_DATABASE_ALLOW_RESET,'true','Explicit isolated-test authorization is required.');
assert(['localhost','127.0.0.1','[::1]','postgres'].includes(parsed.hostname),'Only a local/disposable PostgreSQL host is allowed.');
assert(/^\/madlib_test(?:_[a-z0-9_]+)?$/.test(parsed.pathname),'Database must be madlib_test or madlib_test_<suffix>.');
const schema=`madlib_test_${crypto.randomBytes(8).toString('hex')}`;
const adminPool=new Pool({connectionString:url,max:1,connectionTimeoutMillis:5000});let pool,store,other,sequence=10;
const nextUser=()=>String(200000000000000000n+BigInt(++sequence));
const begin=(st,user,extra={})=>st.begin({guild:IDS.guild,user,name:'A test Squig',templates,cfg,settings,...extra});
const adminArgs=(action,record,revision,extra={})=>({guild:IDS.guild,actor:IDS.user,action,record,revision,evidence:'Verified isolated test evidence; never a live transfer.',...extra});
const bytes=Buffer.from('bounded test staging bytes'),image={bytes,media_type:'image/png',width:64,height:64};
async function finish(s,st=store){while(s.state==='active'){const q=s.template.questions[s.step];s=await st.editSession(s.guild_id,s.user_id,s.id,s.revision,'answer',q.example);}return s;}
async function paid(user=nextUser()){const f=(await begin(store,user)).session;await store.editSession(IDS.guild,user,f.id,f.revision,'abandon');const q=await begin(store,user);assert(q.quote);return (await begin(store,user,{quoteId:q.quote.id})).session;}
async function completed(user=nextUser()){return finish((await begin(store,user)).session);}
async function intent(s,overrides={}){const selected=await store.chooseDraft(IDS.guild,s.user_id,s.id),draft=await store.stage(IDS.guild,s.user_id,s.id,selected.draft.revision,image);return store.publicationIntent(IDS.guild,s.user_id,s.id,draft.revision,{...cfg,...overrides},settings);}
async function published(s,overrides={}){let p=await intent(s,overrides);p=await store.claimPublication(p.id,p.revision);const mid=String(500000000000000000n+BigInt(++sequence));await store.confirmPublication(p.id,{id:mid,attachments:new Collection([['file',{id:`attachment-${mid}`} ]])},p.lease_id);return store.publication(p.id);}
function economyDeps(extra={}){return {
  extractDripCurrencyAmountFromPayload,
  getMarketplaceSpendableBalance:async()=>({ok:true,settings,memberIds:['member-user'],resolvedMember:{id:'member-user'},botMemberId:'member-treasury'}),
  getWalletLinks:async()=>[{verified:true,drip_member_id:'member-user',wallet_address:'0xone'},{verified:true,drip_member_id:'member-user',wallet_address:'0xtwo'}],
  collectDripMemberIdCandidates:m=>[m.id],getDripMemberCurrencyBalance:async()=>10000,clientUserId:()=>IDS.bot,random:()=>0,postAdminSystemLog:async()=>{},
  awardDripPoints:async(realm,ids,amount,currency,settings,o)=>({usedMemberId:ids[0],usedSenderId:o.senderMemberIdOverride,transactionRef:'fake-confirmed-transaction'}),...extra};}
(async()=>{
 try{
  await adminPool.query(`CREATE SCHEMA ${schema}`);pool=new Pool({connectionString:url,max:12,connectionTimeoutMillis:5000,options:`-c search_path=${schema}`});store=new MadlibStore(pool,{random:()=>0});other=new MadlibStore(pool,{random:()=>0.7});
  await run.test('concurrent idempotent migrations touch only feature tables and feature-local foreign keys',async()=>{
    await Promise.all([store.ensureMadlibTables(),other.ensureMadlibTables()]);await store.ensureMadlibTables();
    const names=(await store.query('SELECT tablename FROM pg_tables WHERE schemaname=$1',[schema])).rows.map(r=>r.tablename);assert(names.length>=10);assert(names.every(n=>n.startsWith('madlib_')));assert.equal((await store.one('SELECT version FROM madlib_schema')).version,1);
    const fks=(await store.query("SELECT confrelid::regclass::text AS target FROM pg_constraint WHERE contype='f' AND connamespace=(SELECT oid FROM pg_namespace WHERE nspname=$1)",[schema])).rows;assert(fks.every(r=>r.target.startsWith('madlib_')));
  });
  await run.test('ten simultaneous PLAY calls across processes reserve one free session and zero debits',async()=>{
    const user=nextUser(),results=await Promise.all(Array.from({length:10},(_,i)=>begin(i%2?other:store,user)));assert.equal(new Set(results.map(r=>r.session.id)).size,1);assert.equal(results.filter(r=>!r.resumed).length,1);
    const s=results[0].session,u=await store.one('SELECT * FROM madlib_users WHERE guild_id=$1 AND user_id=$2',[IDS.guild,user]);assert.equal(u.active_session_id,s.id);assert.equal(s.cost,0);assert(Math.abs(u.next_free_at-s.created_at-86400000)<2000);assert.equal((await store.one('SELECT COUNT(*)::int AS n FROM madlib_operations WHERE user_id=$1',[user])).n,0);assert.equal((await other.active(IDS.guild,user)).id,s.id);
  });
  await run.test('one definitely undelivered free reservation restores once; abandonment does not reroll',async()=>{
    const user=nextUser(),s=(await begin(store,user)).session;await store.deliveryAttempt(IDS.guild,user,s.id);assert.equal(await store.restoreUndeliveredFree(IDS.guild,user,s.id),true);
    const replacement=(await begin(other,user)).session;assert.notEqual(s.id,replacement.id);assert.equal(replacement.cost,0);await other.editSession(IDS.guild,user,replacement.id,0,'abandon');assert((await begin(store,user)).quote);assert.equal(await store.restoreUndeliveredFree(IDS.guild,user,s.id),false);
  });
  await run.test('concurrent delivery attempts, delivered and answered sessions cannot reclaim free allowance',async()=>{
    const user=nextUser(),s=(await begin(store,user)).session;await Promise.all([store.deliveryAttempt(IDS.guild,user,s.id),other.deliveryAttempt(IDS.guild,user,s.id)]);assert.equal(await store.restoreUndeliveredFree(IDS.guild,user,s.id),false);await store.delivered(IDS.guild,user,s.id);assert.equal(await store.restoreUndeliveredFree(IDS.guild,user,s.id),false);
    const u2=nextUser();let s2=(await begin(store,u2)).session;s2=await store.editSession(IDS.guild,u2,s2.id,0,'answer','hopeful');assert.equal(await store.restoreUndeliveredFree(IDS.guild,u2,s2.id),false);
  });
  await run.test('confirmation rechecks rolling boundary and uses a newly free play instead of charging',async()=>{
    const user=nextUser(),first=(await begin(store,user)).session;await store.editSession(IDS.guild,user,first.id,0,'abandon');const quote=(await begin(store,user)).quote;assert(quote);
    await store.query("UPDATE madlib_users SET next_free_at=clock_timestamp()-interval '1 millisecond' WHERE guild_id=$1 AND user_id=$2",[IDS.guild,user]);const s=(await begin(store,user,{quoteId:quote.id})).session;assert.equal(s.cost,0);assert.equal(s.state,'active');assert.equal(await store.operation(`madlib_play:${s.id}`),null);
  });
  await run.test('expired quotes and changed prices require new confirmation without a debit',async()=>{
    const user=nextUser(),f=(await begin(store,user)).session;await store.editSession(IDS.guild,user,f.id,0,'abandon');const q1=(await begin(store,user)).quote;await store.query("UPDATE madlib_quotes SET expires_at=now()-interval '1 second' WHERE id=$1",[q1.id]);const q2=(await begin(store,user,{quoteId:q1.id})).quote;assert(q2&&q2.id!==q1.id);const q3=(await begin(store,user,{quoteId:q2.id,cfg:{...cfg,MADLIB_EXTRA_PLAY_COST_CHARM:1200}})).quote;assert.equal(q3.amount,1200);assert.equal(await store.active(IDS.guild,user),null);
  });
  await run.test('parallel paid confirmations and workers send once and never move the free clock',async()=>{
    const user=nextUser(),f=(await begin(store,user)).session;await store.editSession(IDS.guild,user,f.id,0,'abandon');const before=await store.one('SELECT next_free_at FROM madlib_users WHERE guild_id=$1 AND user_id=$2',[IDS.guild,user]),q=(await begin(store,user)).quote;
    const results=await Promise.all(Array.from({length:8},(_,i)=>begin(i%2?other:store,user,{quoteId:q.id})));assert.equal(new Set(results.map(r=>r.session.id)).size,1);const s=results[0].session;assert.equal(s.cost,1000);assert.equal((await store.one('SELECT COUNT(*)::int AS n FROM madlib_operations WHERE session_id=$1',[s.id])).n,1);assert.equal((await store.one('SELECT next_free_at FROM madlib_users WHERE guild_id=$1 AND user_id=$2',[IDS.guild,user])).next_free_at.getTime(),before.next_free_at.getTime());
    let sends=0;const deps=economyDeps({awardDripPoints:async(r,ids,n,c,settings,o)=>{sends++;assert.equal(n,1000);assert.equal(c,'test-charm');assert.deepEqual(ids,['member-treasury']);assert.equal(o.senderMemberIdOverride,'member-user');assert.equal(o.recipientDiscordId,IDS.bot);assert.equal(o.requireTransfer,true);assert.equal(o.madlibStrictTransfer,true);await new Promise(r=>setTimeout(r,20));return {usedMemberId:ids[0],usedSenderId:o.senderMemberIdOverride};}});
    await Promise.all(Array.from({length:8},(_,i)=>new MadlibEconomy(i%2?other:store,deps).execute(`madlib_play:${s.id}`)));assert.equal(sends,1);assert.equal((await store.operation(`madlib_play:${s.id}`)).attempt_count,1);assert.equal((await store.owned(IDS.guild,user,s.id)).state,'active');
  });
  await run.test('duplicate answers save once; Back, restart and completed outputs retain the exact snapshot',async()=>{
    const user=nextUser();let s=(await begin(store,user)).session;const results=await Promise.allSettled([store.editSession(IDS.guild,user,s.id,0,'answer','delighted'),other.editSession(IDS.guild,user,s.id,0,'answer','furious')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.find(r=>r.status==='rejected').reason.code,'STALE');s=await other.owned(IDS.guild,user,s.id);assert.equal(s.step,1);const first=s.answers[s.template.questions[0].key];s=await other.editSession(IDS.guild,user,s.id,s.revision,'back');assert.equal(s.step,0);assert.equal(s.answers[s.template.questions[0].key],first);
    await assert.rejects(()=>store.owned(IDS.otherGuild,user,s.id),errorCode('OWNER'));await assert.rejects(()=>store.editSession(IDS.guild,IDS.other,s.id,s.revision,'answer','stolen'),errorCode('OWNER'));s=await finish(s,other);assert(s.story&&s.prompt);const saved=s.prompt,oldTitle=templates[0].title;templates[0].title='Edited after completion';try{assert.equal((await store.owned(IDS.guild,user,s.id)).prompt,saved);}finally{templates[0].title=oldTitle;}assert.equal(await store.active(IDS.guild,user),null);assert.equal((await store.history(IDS.guild,user))[0].id,s.id);
  });
  await run.test('zero and unknown balances send nothing and leave an inspectable failed session',async()=>{
    for(const balance of [0,null]){const s=await paid();let sends=0;const e=new MadlibEconomy(store,economyDeps({getDripMemberCurrencyBalance:async()=>balance,awardDripPoints:async()=>{sends++;}})),result=await e.execute(`madlib_play:${s.id}`);assert.equal(result.state,'confirmed_failure');assert.equal(sends,0);const op=await store.operation(result.operationId);assert.equal(op.attempt_count,0);assert.equal(op.error_code,balance===0?'INSUFFICIENT_FUNDS':'BALANCE_UNKNOWN');assert.equal((await store.active(IDS.guild,s.user_id)).state,'payment_failed');}
  });
  await run.test('BALANCE_UNKNOWN can be retried once on the same intent using Marketplace member balance',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`;let sends=0,direct=0;
    const before=await store.one('SELECT next_free_at FROM madlib_users WHERE guild_id=$1 AND user_id=$2',[IDS.guild,s.user_id]);
    const broken=new MadlibEconomy(store,economyDeps({getDripMemberCurrencyBalance:async()=>null,awardDripPoints:async()=>{sends++;}}));
    assert.equal((await broken.execute(id)).code,'BALANCE_UNKNOWN');let op=await store.operation(id);assert.equal(op.attempt_count,0);assert.equal(sends,0);
    await store.admin(adminArgs('retry',id,op.revision));
    const fixed=economyDeps({getMarketplaceSpendableBalance:async()=>({ok:true,settings,memberIds:['member-user'],resolvedMember:{id:'member-user',balances:[{currencyId:'test-charm',balance:10000}]},botMemberId:'member-treasury'}),getDripMemberCurrencyBalance:async()=>{direct++;throw Error('404');},awardDripPoints:async(r,ids,n,c,settings,o)=>{sends++;return {usedMemberId:ids[0],usedSenderId:o.senderMemberIdOverride};}});
    await Promise.all([new MadlibEconomy(store,fixed).execute(id),new MadlibEconomy(other,fixed).execute(id)]);
    assert.equal(sends,1);assert.equal(direct,0);op=await store.operation(id);assert.equal(op.state,'confirmed_success');assert.equal(op.attempt_count,1);
    assert.equal((await store.active(IDS.guild,s.user_id)).id,s.id);assert.equal((await store.active(IDS.guild,s.user_id)).state,'active');
    assert.equal((await store.one('SELECT next_free_at FROM madlib_users WHERE guild_id=$1 AND user_id=$2',[IDS.guild,s.user_id])).next_free_at.getTime(),before.next_free_at.getTime());
    await assert.rejects(()=>store.admin(adminArgs('retry',id,op.revision)),errorCode('STATE'));assert.equal(await other.claimOperation(id),null);
  });
  await run.test('expired resolving lease can be reclaimed but its former worker cannot arm',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`,old=await store.claimOperation(id);await store.query("UPDATE madlib_operations SET lease_until=now()-interval '1 second' WHERE id=$1",[id]);await other.recoverStale();const fresh=await other.claimOperation(id);assert(fresh);assert.notEqual(fresh.lease_id,old.lease_id);assert.equal(await store.armOperation(old,{sender:'member-user',recipient:'member-treasury'}),null);const armed=await other.armOperation(fresh,{sender:'member-user',recipient:'member-treasury'});assert(armed);assert.equal(armed.attempt_count,1);
  });
  await run.test('expired in-flight operation is held for review; restart cannot resend or abandon it',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`,op=await store.claimOperation(id);await store.armOperation(op,{sender:'member-user',recipient:'member-treasury'});await store.query("UPDATE madlib_operations SET lease_until=now()-interval '1 second' WHERE id=$1",[id]);await other.recoverStale();assert.equal((await store.operation(id)).state,'needs_review');assert.equal((await store.owned(IDS.guild,s.user_id,s.id)).state,'payment_review');assert.equal(await other.claimOperation(id),null);assert((await begin(other,s.user_id)).resumed);const current=await store.owned(IDS.guild,s.user_id,s.id);await assert.rejects(()=>store.editSession(IDS.guild,s.user_id,s.id,current.revision,'abandon'),errorCode('PAYMENT'));
  });
  await run.test('provider success with lost database acknowledgement needs evidence; mark-sent never sends',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`;let sends=0;const broken=Object.create(store);broken.finishOperation=async()=>{throw new Error('Simulated lost database acknowledgement');};const deps=economyDeps({awardDripPoints:async(r,ids,n,c,settings,o)=>{sends++;return {usedMemberId:ids[0],usedSenderId:o.senderMemberIdOverride};}});assert.equal((await new MadlibEconomy(broken,deps).execute(id)).state,'needs_review');await new MadlibEconomy(other,deps).execute(id);assert.equal(sends,1);
    let op=await store.operation(id);await assert.rejects(()=>store.admin(adminArgs('mark-sent',id,op.revision)),errorCode('STATE'));await store.query("UPDATE madlib_operations SET sent_at=now()-interval '6 minutes' WHERE id=$1",[id]);op=await store.operation(id);await store.admin(adminArgs('mark-sent',id,op.revision));assert.equal(sends,1);assert.equal((await store.owned(IDS.guild,s.user_id,s.id)).state,'active');await assert.rejects(()=>other.admin(adminArgs('mark-sent',id,op.revision)),errorCode('STALE'));assert.equal((await store.one('SELECT COUNT(*)::int AS n FROM madlib_audit WHERE record_id=$1',[id])).n,1);
  });
  await run.test('authoritative not-sent evidence unlocks retry, but abandoned failed plays cannot be charged',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`,op=await store.claimOperation(id),armed=await store.armOperation(op,{sender:'member-user',recipient:'member-treasury'});await store.failOperation(armed,'TRANSFER_UNCERTAIN',{uncertain:true});await store.query("UPDATE madlib_operations SET sent_at=now()-interval '6 minutes' WHERE id=$1",[id]);let o=await store.operation(id);await assert.rejects(()=>store.admin(adminArgs('retry',id,o.revision)),errorCode('STATE'));o=await store.admin(adminArgs('mark-not-sent',id,o.revision));assert.equal(o.state,'confirmed_failure');o=await store.admin(adminArgs('retry',id,o.revision));assert.equal(o.state,'prepared');assert.equal((await store.owned(IDS.guild,s.user_id,s.id)).state,'awaiting_payment');const current=await store.claimOperation(id);await store.failOperation(current,'INSUFFICIENT_FUNDS');const saved=await store.owned(IDS.guild,s.user_id,s.id);await store.editSession(IDS.guild,s.user_id,s.id,saved.revision,'abandon');o=await store.operation(id);await assert.rejects(()=>store.admin(adminArgs('retry',id,o.revision)),errorCode('STATE'));
  });
  await run.test('financial pause blocks claiming and arming, not free play or saved data; revisions and evidence are mandatory',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`,resolving=await store.claimOperation(id);let g=(await store.status(IDS.guild)).guild;await assert.rejects(()=>store.admin(adminArgs('pause',IDS.guild,g.revision,{evidence:'x'})),errorCode('EVIDENCE'));g=await store.admin(adminArgs('pause',IDS.guild,g.revision));assert(g.finances_paused);await assert.rejects(()=>store.armOperation(resolving,{sender:'member-user',recipient:'member-treasury'}),errorCode('PAUSED'));assert.equal(await other.claimOperation(),null);const user=nextUser(),free=(await begin(store,user)).session;assert.equal(free.state,'active');await store.editSession(IDS.guild,user,free.id,0,'abandon');const quote=(await begin(store,user)).quote;await assert.rejects(()=>begin(store,user,{quoteId:quote.id}),errorCode('PAUSED'));await store.admin(adminArgs('resume',IDS.guild,g.revision));await store.failOperation(resolving,'PAUSED');
  });
  await run.test('documented system-failure refund reverses the original member currency and amount once',async()=>{
    const s=await paid(),id=`madlib_play:${s.id}`,e=new MadlibEconomy(store,economyDeps());await e.execute(id);const original=await store.operation(id),refund=await store.admin(adminArgs('refund',id,original.revision));assert.equal(refund.amount,1000);assert.equal(refund.sender_id,'member-treasury');assert.equal(refund.recipient_id,'member-user');assert.equal(refund.currency_id,'test-charm');assert.equal((await store.active(IDS.guild,s.user_id)).state,'refund_pending');await assert.rejects(()=>store.admin(adminArgs('refund',id,original.revision)),errorCode('STATE'));await e.execute(refund.id);assert.equal((await store.owned(IDS.guild,s.user_id,s.id)).state,'refunded');assert.equal(await store.active(IDS.guild,s.user_id),null);assert.equal((await store.operation(id)).state,'confirmed_success');assert.equal(await other.claimOperation(refund.id),null);
  });
  await run.test('staged bytes persist across stores with owner and preview revision guards and fixed expiry',async()=>{
    const s=await completed(),selected=await store.chooseDraft(IDS.guild,s.user_id,s.id),staged=await store.stage(IDS.guild,s.user_id,s.id,selected.draft.revision,image);assert((await other.upload(s.id)).bytes.equals(bytes));const expiry=(await other.upload(s.id)).expires_at,reopened=await other.chooseDraft(IDS.guild,s.user_id,s.id);assert(reopened.draft.revision>staged.revision);assert.equal((await store.upload(s.id)).revision,reopened.draft.revision);assert.equal((await store.upload(s.id)).expires_at.getTime(),expiry.getTime());await assert.rejects(()=>store.stage(IDS.guild,IDS.other,s.id,reopened.draft.revision,image),errorCode('OWNER'));await assert.rejects(()=>store.stage(IDS.guild,s.user_id,s.id,staged.revision,image),errorCode('STALE'));await store.cancelUpload(IDS.guild,s.user_id,s.id,reopened.draft.revision);assert.equal(await store.upload(s.id),null);assert((await store.history(IDS.guild,s.user_id)).length);
    const d=(await store.chooseDraft(IDS.guild,s.user_id,s.id)).draft;await store.stage(IDS.guild,s.user_id,s.id,d.revision,image);await store.query("UPDATE madlib_uploads SET expires_at=now()-interval '1 second' WHERE session_id=$1",[s.id]);await other.recoverStale();assert.equal(await store.upload(s.id),null);assert.equal((await store.owned(IDS.guild,s.user_id,s.id)).state,'completed');
  });
  await run.test('parallel publication intents yield one lifetime identity and a single approved-revision send claim',async()=>{
    const s=await completed(),d=(await store.chooseDraft(IDS.guild,s.user_id,s.id)).draft,staged=await store.stage(IDS.guild,s.user_id,s.id,d.revision,image),rows=await Promise.all(Array.from({length:6},(_,i)=>(i%2?other:store).publicationIntent(IDS.guild,s.user_id,s.id,staged.revision,cfg,settings)));assert.equal(new Set(rows.map(p=>p.id)).size,1);const p=rows[0],reopened=await other.chooseDraft(IDS.guild,s.user_id,s.id);assert.equal((await store.publication(p.id)).upload_revision,reopened.draft.revision);assert.equal(await store.claimPublication(p.id,p.revision),null);const latest=await store.publication(p.id),claims=await Promise.all([store.claimPublication(p.id,latest.revision),other.claimPublication(p.id,latest.revision)]);assert.equal(claims.filter(Boolean).length,1);await assert.rejects(()=>store.stage(IDS.guild,s.user_id,s.id,reopened.draft.revision,image),errorCode('PUBLISHED'));await store.query("UPDATE madlib_publications SET lease_until=now()-interval '1 second' WHERE id=$1",[p.id]);await store.recoverStale();assert.equal((await store.publication(p.id)).status,'needs_review');assert.equal(await store.claimPublication(p.id,999),null);
  });
  await run.test('uncertain public send reconciles to the existing stable marker with no second send',async()=>{
    const s=await completed(),p=await intent(s),fake=fakeDiscord();let sentMessage,sends=0;fake.channel.send=async payload=>{sends++;sentMessage={id:String(500000000000000000n+BigInt(++sequence)),author:{id:IDS.bot},guildId:IDS.guild,embeds:payload.embeds.map(e=>e.toJSON()),createdTimestamp:Date.now(),attachments:new Collection([['a',{id:'a'}]]),react:async()=>{}};throw new Error('Connection lost after accepted send');};const deps={client:fake.client,clientUserId:()=>IDS.bot,postAdminSystemLog:async()=>{}},publisher=new MadlibPublishing(store,deps,cfg);await publisher.publish(p);assert.equal((await store.publication(p.id)).status,'needs_review');assert.equal(sends,1);fake.channel.messages.fetch=async()=>new Collection([[sentMessage.id,sentMessage]]);await publisher.reconcileUncertain(await store.publication(p.id),fake.channel);assert.equal((await other.publication(p.id)).message_id,sentMessage.id);await publisher.publish(await store.publication(p.id));assert.equal(sends,1);assert.equal(await store.upload(s.id),null);assert.equal(sentMessage.embeds[0].footer.text,marker(p));
  });
  await run.test('Gateway and normal/burst reconciliation duplicates create one author reward, never a reactor payout',async()=>{
    const s=await completed(),p=await published(s),reactor=nextUser(),records=await Promise.all(Array.from({length:8},(_,i)=>(i%2?other:store).recordReaction(p,reactor)));assert.equal(records.filter(Boolean).length,1);const op=await store.operation(records.find(Boolean));assert.equal(op.user_id,s.user_id);assert.equal(op.reactor_id,reactor);assert.equal(op.amount,100);assert.equal(op.currency_id,'test-charm');assert.equal(await other.recordReaction(p,s.user_id),null);assert.equal(await other.recordReaction(p,reactor),null);let recipientUser;const e=new MadlibEconomy(store,economyDeps({getWalletLinks:async(g,u)=>{recipientUser=u;return [{verified:true,drip_member_id:'member-user'}];}}));await e.execute(op.id);assert.equal(recipientUser,s.user_id);const totals=await store.totals(p.id);assert.equal(totals.eligible,1);assert.equal(String(totals.paid),'100');assert.equal(String(totals.pending),'0');assert.equal(await store.recordReaction(p,reactor),null);
  });
  await run.test('default rewards remain uncapped after 100 reactions and on old posts; snapshots are immutable',async()=>{
    const s=await completed(),p=await published(s);await store.query("UPDATE madlib_publications SET created_at=now()-interval '400 days' WHERE id=$1",[p.id]);for(let i=0;i<105;i++)assert(await store.recordReaction({...p,reward:999},nextUser()));const totals=await store.totals(p.id);assert.equal(totals.eligible,105);assert.equal(String(totals.pending),'10500');assert.equal(String(totals.paid),'0');const capped=await published(await completed(),{MADLIB_REWARD_CAP_PER_POST:200});assert(await store.recordReaction(capped,nextUser()));assert(await store.recordReaction(capped,nextUser()));assert.equal(await store.recordReaction(capped,nextUser()),null);
  });
  await run.test('missing author DRIP setup retains a retryable obligation until identity recovers',async()=>{
    const s=await completed(),p=await published(s),id=await store.recordReaction(p,nextUser());let calls=0;const e=new MadlibEconomy(store,economyDeps({getMarketplaceSpendableBalance:async()=>({ok:false}),awardDripPoints:async()=>{calls++;}}));assert.equal((await e.execute(id)).state,'retryable_failure');assert.equal(calls,0);assert.equal(String((await store.totals(p.id)).pending),'100');await store.query('UPDATE madlib_operations SET next_attempt_at=now() WHERE id=$1',[id]);await new MadlibEconomy(other,economyDeps()).execute(id);assert.equal(String((await store.totals(p.id)).paid),'100');
  });
  await run.test('moderation stops future awards; deletion retains identity and previously earned obligations',async()=>{
    const s=await completed();let p=await published(s);const op=await store.recordReaction(p,nextUser());p=await store.admin(adminArgs('suspend',p.id,p.revision));assert.equal(await store.recordReaction(p,nextUser()),null);assert.equal((await store.operation(op)).state,'prepared');p=await store.admin(adminArgs('unsuspend',p.id,p.revision));assert(await store.recordReaction(p,nextUser()));await store.query("UPDATE madlib_publications SET status='deleted' WHERE id=$1",[p.id]);assert.equal(await store.recordReaction(p,nextUser()),null);const selected=await store.chooseDraft(IDS.guild,s.user_id,s.id);assert.equal(selected.publication.id,p.id);assert.equal(selected.publication.status,'deleted');assert.equal((await store.operation(op)).state,'prepared');await assert.rejects(()=>store.stage(IDS.guild,s.user_id,s.id,0,image),errorCode('PUBLISHED'));
  });
  await run.test('due reconciliation selects old posts fairly and persists normal/burst cursors with lease protection',async()=>{
    await store.query("UPDATE madlib_publications SET next_reconcile_at=now()+interval '1 day',lease_until=NULL");const a=await published(await completed()),b=await published(await completed());await store.query("UPDATE madlib_publications SET next_reconcile_at=now()-interval '2 days' WHERE id=$1",[a.id]);const pa=await store.claimReconcile();assert.equal(pa.id,a.id);const pb=await other.claimReconcile();assert.equal(pb.id,b.id);await store.releaseReconcile(pa,{after:'999999999999999999',type:1,delay:300});const saved=await other.publication(a.id);assert.equal(saved.reconcile_type,1);assert.equal(saved.reconcile_after,'999999999999999999');await store.releaseReconcile({...pa,lease_id:'stale-lease'},{after:'1',type:0,delay:1});assert.equal((await store.publication(a.id)).reconcile_after,'999999999999999999');await store.releaseReconcile(pb,{deleted:true});assert.equal((await store.publication(b.id)).status,'deleted');
  });
  await run.test('older history remains paginated and feature-local foreign keys retain payment audits',async()=>{
    const user=nextUser(),first=await completed(user);for(let i=0;i<22;i++)await store.query(`INSERT INTO madlib_sessions(id,guild_id,user_id,display_name,template_id,template_version,template,state,story,prompt,completed_at) VALUES($1,$2,$3,'History fixture',$4,1,$5,'completed',$6,$7,now()-($8::int*interval '1 hour'))`,[core.id(),IDS.guild,user,first.template_id,JSON.stringify(first.template),first.story,first.prompt,i+1]);assert.equal((await store.history(IDS.guild,user,0)).length,21);assert.equal((await other.history(IDS.guild,user,1)).length,3);assert.equal((await store.history(IDS.guild,user,0))[0].id,first.id);await assert.rejects(()=>store.history(IDS.guild,user,-1),errorCode('PAGE'));const p=await published(first);await store.recordReaction(p,nextUser());await assert.rejects(()=>store.query('DELETE FROM madlib_publications WHERE id=$1',[p.id]),e=>e.code==='23503');
  });
  run.done();console.log(`PostgreSQL version: ${(await store.one('SHOW server_version')).server_version}; disposable schema tests completed.`);
 }finally{if(pool)await pool.end();await adminPool.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`).finally(()=>adminPool.end());}
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
